### ISSUE TITLE
[Crash] Raft Java Exception

### ISSUE THREAD

**Issue by artdude543** [Mrbysco/JustARaftMod#5]
Hello!

A developer of SevTech here. I've just got a crash report from a user in regards to the raft in your mod the log is here: https://pastebin.com/Xf7SSg93

Version: 1.1

Would it be possible for you to look into/fix the issue, please?

Thanks!

**Comment by Mrbysco** [comment]
Will look into

**Comment by Mrbysco** [comment]
I think some mod is modifying boat code which changes my raft as I extend the EntityBoat

**Comment by Mrbysco** [comment]
I'm unable to reproduce it

**Comment by Mrbysco** [comment]
Added a (float) cast where it's somehow getting an int to see if that would fix it.

**Comment by SharkWipf** [comment]
For people running into this still (it suddenly started happening for us with a raft that's been sitting in our base with a skeleton on top for months), 
- It only happens during login when the game hasn't fully loaded yet
- You can work around it by getting an admin to teleport you away from the raft as soon as you log in, if you're fast enough you won't crash, otherwise you'll be able to join properly on the next login.

EDIT: On closer inspection it looks like our issue is closely related/very similar to this issue, but not exactly the same. Workaround is probably the same. Attaching my log: https://pastebin.com/qpGApUHj

**Comment by SharkWipf** [comment]
The raft in question, btw: 
![image](https://user-images.githubusercontent.com/751205/53442728-3a143e80-3a0a-11e9-87bd-f2e9eae890eb.png)
As you can tell, can properly see it after logging in without any crashes.
Any more info I can get to help debug this?
